### ISSUE TITLE
Not launching in Mac OS Mojave 10.14

### ISSUE THREAD

**Issue by massisenergy** [ChristianFJanssen/jflowsim#5]
When `java jflowsim.Program` is run in terminal, it goes into Java but then it halts without opening any window. The following error appears in terminal:

> javax.swing.UnsupportedLookAndFeelException: [The Microsoft Windows Look and Feel - com.sun.java.swing.plaf.windows.WindowsLookAndFeel] not supported on this platform
	at java.desktop/javax.swing.UIManager.setLookAndFeel(UIManager.java:574)
	at java.desktop/javax.swing.UIManager.setLookAndFeel(UIManager.java:632)
	at jflowsim.view.MainWindow.<init>(MainWindow.java:60)
	at jflowsim.Program.main(Program.java:25)
Exception in thread "main" java.lang.NullPointerException
	at java.desktop/javax.swing.ImageIcon.<init>(ImageIcon.java:217)
	at jflowsim.view.img.ImageUtilities.createImageIcon(ImageUtilities.java:28)
	at jflowsim.view.configdialog.ConfigDialog.<init>(ConfigDialog.java:30)
	at jflowsim.view.MainWindow.<init>(MainWindow.java:70)
	at jflowsim.Program.main(Program.java:25)

**Comment by biels** [comment]
It looks like the images are not included in the repo:
![image](https://user-images.githubusercontent.com/5158960/70933039-6a7da580-203b-11ea-83f0-f077b3cbe030.png)
This folder should come along with it

**Comment by crohr88** [comment]
That folder appears to be in the correct location and in the repo?

**Comment by crohr88** [comment]
I was having the same issue on Windows. The resources could never be found and there was a method trying to get them that always returned null, preventing the GUI from loading. 

The problem was that the classpath needs to be set to the src folder explicitly on compilation. Only this exact combination worked, trying to compile in any other way would appear successful but then error when running. 

cd to the src folder, then 
`javac -cp . ./jflowsim/Program.java`
You should now be able to successfully launch the program with the following:
`java jflowsim.Program`

Thank you to Vladimir B. on upwork who helped me figure this out.
